// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFrhR9K8H4C90asuvKWANdU32ksNwcgc',
    appId: '1:617093228331:web:82ae45eed84455deb4476e',
    messagingSenderId: '617093228331',
    projectId: 'sleepy-detection',
    authDomain: 'sleepy-detection.firebaseapp.com',
    storageBucket: 'sleepy-detection.appspot.com',
    measurementId: 'G-1FWRN48RM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvt4-ANc8oAiV7HKElS5CDZ2iux5VUYgA',
    appId: '1:617093228331:android:2d126ae3c149d1ebb4476e',
    messagingSenderId: '617093228331',
    projectId: 'sleepy-detection',
    storageBucket: 'sleepy-detection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfNbknVSCQ2U-1BMJEgfntWRSYYjCUNwg',
    appId: '1:617093228331:ios:1d31c7aed1759943b4476e',
    messagingSenderId: '617093228331',
    projectId: 'sleepy-detection',
    storageBucket: 'sleepy-detection.appspot.com',
    iosBundleId: 'com.example.driverDrowsinessAlert',
  );
}
